#include <stdio.h>
// #include <string.h>
#include "../../s21_string.h"

int main() {
  char *base = "|\t* *lancer* *\t|";
  char *base_empty = "";
  char *base_null = NULL;
  char *base_wtf = " \ti fd\nuteil  56\0tr65 \tge  ";
  char *base_check = "lance|";
  char *remove = "|\tlec";
  char *remove_char = "|";
  char *remove_char2 = "|\t";
  char *remove_char3 = "|*\t";
  char *remove_char4 = "'|* l\t";
  char *remove_letter = "ltp";
  char *remove_empty = "";
  char *remove_end = "\0";
  int i = 0;
  char *res1 = NULL;
  char *res2 = NULL;
  char *res3 = NULL;
  char *res4 = NULL;
  char *res5 = NULL;
  char *res6 = NULL;
  char *res7 = NULL;
  char *res8 = NULL;
  char *res9 = NULL;
  char *res10 = NULL;
  char *res11 = NULL;
  char *res12 = NULL;
  char *res13 = NULL;
  res1 = s21_trim(base, remove);
  res2 = s21_trim(base, remove_empty);
  res3 = s21_trim(base_null, remove);
  res4 = s21_trim(base_empty, remove_empty);
  res5 = s21_trim(base, remove_letter);
  res6 = s21_trim(base, remove_char);
  res7 = s21_trim(base, remove_char2);
  res8 = s21_trim(base, remove_char3);
  res9 = s21_trim(base, remove_char4);
  res10 = s21_trim(base_wtf, remove_char4);
  res11 = s21_trim(base_wtf, remove_end);
  res12 = s21_trim(base, remove_end);
  res13 = s21_trim(base_check, remove);
  printf("#%d <%s> - исходник\n", i, base);
  i++;
  printf("#%d <%s>\n", i, res1);
  i++;
  printf("#%d <%s>\n", i, res2);
  i++;
  printf("#%d <%s>\n", i, res3);
  i++;
  printf("#%d <%s>\n", i, res4);
  i++;
  printf("#%d <%s>\n", i, res5);
  i++;
  printf("#%d <%s>\n", i, res6);
  i++;
  printf("#%d <%s>\n", i, res7);
  i++;
  printf("#%d <%s>\n", i, res8);
  i++;
  printf("#%d <%s>\n", i, res9);
  i++;
  printf("#%d <%s>\n", i, res10);
  i++;
  printf("#%d <%s>\n", i, res11);
  i++;
  printf("#%d <%s>\n", i, res12);
  i++;
  printf("#%d <%s>\n", i, res13);
  i++;
  return 0;
}